"""
============================================================
 t3d_parser.py
 UE4 材质编辑器 T3D 剪贴板文本解析器
============================================================

解析从 UE4 材质编辑器 Ctrl+C 复制出来的 T3D 格式文本，
还原为内部数据结构（MaterialGraph），以供可视化和重新导出。

T3D 格式示例：
  Begin Object Class=/Script/UnrealEd.MaterialGraphNode Name="MaterialGraphNode_0" ...
     Begin Object Class=/Script/Engine.MaterialExpressionAdd Name="MaterialExpressionAdd_0" ...
     End Object
     Begin Object Name="MaterialExpressionAdd_0"
        ...属性...
     End Object
     MaterialExpression=MaterialExpressionAdd'"MaterialExpressionAdd_0"'
     NodePosX=320
     NodePosY=240
     CustomProperties Pin (PinId=...,PinName="A",LinkedTo=(...),...)
  End Object
============================================================
"""

import re
import uuid
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Any


# ═══════════════════════════════════════════════════════════
# 数据结构
# ═══════════════════════════════════════════════════════════

@dataclass
class T3DPin:
    """一个引脚"""
    pin_id: str = ''
    pin_name: str = ''
    pin_friendly_name: str = ''
    direction: str = 'EGPD_Input'  # EGPD_Input 或 EGPD_Output
    pin_type_category: str = ''
    pin_type_sub_category: str = ''
    pin_type_sub_category_object: str = 'None'
    default_value: str = ''
    autogenerated_default_value: str = ''
    linked_to: List[Tuple[str, str]] = field(default_factory=list)  # [(NodeName, PinGuid), ...]
    persistent_guid: str = '00000000000000000000000000000000'
    is_hidden: bool = False
    is_not_connectable: bool = False
    is_advanced_view: bool = False
    is_orphaned: bool = False
    # 原始属性 dict（保存所有未识别的属性）
    raw_props: Dict[str, str] = field(default_factory=dict)


@dataclass
class T3DInnerObject:
    """嵌套的内部对象（如 MaterialExpression）"""
    class_path: str = ''   # e.g. /Script/Engine.MaterialExpressionAdd
    class_name: str = ''   # e.g. MaterialExpressionAdd
    name: str = ''         # e.g. MaterialExpressionAdd_0
    archetype: str = ''
    properties: Dict[str, str] = field(default_factory=dict)


@dataclass
class T3DGraphNode:
    """一个材质图节点"""
    class_path: str = ''   # e.g. /Script/UnrealEd.MaterialGraphNode
    name: str = ''         # e.g. MaterialGraphNode_0
    archetype: str = ''
    node_pos_x: int = 0
    node_pos_y: int = 0
    node_guid: str = ''
    # 嵌套的 MaterialExpression
    material_expression: Optional[T3DInnerObject] = None
    material_expression_ref: str = ''  # MaterialExpression=...行的原始值
    # 引脚列表
    pins: List[T3DPin] = field(default_factory=list)
    # 所有属性（包括未识别的）
    properties: Dict[str, str] = field(default_factory=dict)
    # 错误信息
    error_messages: List[str] = field(default_factory=list)


@dataclass
class T3DParseResult:
    """解析结果"""
    nodes: List[T3DGraphNode] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    raw_text: str = ''


# ═══════════════════════════════════════════════════════════
# 字符串转义处理
# ═══════════════════════════════════════════════════════════

def _unescape_t3d_string(s: str) -> str:
    """反转义 T3D 属性字符串
    
    T3D 中字符串属性（如 Code）使用的转义序列：
      \\r\\n  → 换行（CRLF，优先处理）
      \\n    → 换行（LF）
      \\r    → 回车（CR）
      \\t    → tab
      \\"    → 引号
      \\\\    → 反斜杠
    """
    if not s:
        return s
    
    # 先处理双反斜杠，用占位符暂存，避免干扰后续替换
    PLACEHOLDER = '\x00BACKSLASH\x00'
    s = s.replace('\\\\', PLACEHOLDER)
    
    # 转义序列替换（Windows 风格 CRLF 优先处理）
    s = s.replace('\\r\\n', '\n')
    s = s.replace('\\r', '\r')
    s = s.replace('\\n', '\n')
    s = s.replace('\\t', '\t')
    s = s.replace('\\"', '"')
    
    # 还原真正的反斜杠
    s = s.replace(PLACEHOLDER, '\\')
    return s


# ═══════════════════════════════════════════════════════════
# 解析核心
# ═══════════════════════════════════════════════════════════

class T3DParser:
    """解析 UE4 T3D 剪贴板文本"""

    def __init__(self):
        # 正则模式
        self._re_begin = re.compile(
            r'^\s*Begin\s+Object'
            r'(?:\s+Class=([^\s]+))?'
            r'(?:\s+Name="([^"]*)")?'
            r'(?:\s+Archetype=(.+))?',
            re.IGNORECASE
        )
        self._re_end = re.compile(r'^\s*End\s+Object', re.IGNORECASE)
        self._re_property = re.compile(r'^\s+(\w[\w.]*)\s*=\s*(.*?)\s*$')
        self._re_custom_pin = re.compile(r'^\s+CustomProperties\s+Pin\s+\((.+)\)\s*$', re.IGNORECASE)

    def parse(self, text: str) -> T3DParseResult:
        """解析完整的 T3D 文本"""
        result = T3DParseResult(raw_text=text)

        if not text or not text.strip():
            result.errors.append('输入文本为空')
            return result

        # 规范化换行
        text = text.replace('\r\n', '\n').replace('\r', '\n')
        lines = text.split('\n')

        # 解析顶层对象
        i = 0
        while i < len(lines):
            line = lines[i]
            m = self._re_begin.match(line)
            if m:
                node, end_i = self._parse_graph_node(lines, i)
                if node:
                    result.nodes.append(node)
                    if node.error_messages:
                        result.warnings.extend(node.error_messages)
                i = end_i + 1
            else:
                i += 1

        if not result.nodes:
            result.errors.append('未找到任何 Begin Object 块，请确认是从 UE4 材质编辑器复制的节点文本')

        # 验证连线引用
        node_names = {n.name for n in result.nodes}
        for node in result.nodes:
            for pin in node.pins:
                for target_node, target_pin_id in pin.linked_to:
                    if target_node not in node_names:
                        result.warnings.append(
                            f'节点 {node.name} 的 Pin "{pin.pin_name}" 引用了不存在的节点 {target_node}'
                            f'（可能该节点未被选中复制）'
                        )

        return result

    def _parse_graph_node(self, lines: List[str], start: int) -> Tuple[Optional[T3DGraphNode], int]:
        """解析一个顶层 Begin Object ... End Object 块"""
        m = self._re_begin.match(lines[start])
        if not m:
            return None, start

        node = T3DGraphNode()
        node.class_path = m.group(1) or ''
        node.name = m.group(2) or ''
        node.archetype = m.group(3) or ''

        depth = 1
        i = start + 1
        inner_objects: List[T3DInnerObject] = []

        while i < len(lines) and depth > 0:
            line = lines[i]

            # 检查 End Object
            if self._re_end.match(line):
                depth -= 1
                if depth == 0:
                    break
                i += 1
                continue

            # 检查嵌套 Begin Object（内部 MaterialExpression 对象）
            m_inner = self._re_begin.match(line)
            if m_inner and depth == 1:
                inner_obj, end_i = self._parse_inner_object(lines, i)
                if inner_obj:
                    inner_objects.append(inner_obj)
                i = end_i + 1
                continue

            # 检查 CustomProperties Pin
            m_pin = self._re_custom_pin.match(line)
            if m_pin and depth == 1:
                pin = self._parse_pin(m_pin.group(1))
                node.pins.append(pin)
                i += 1
                continue

            # 普通属性
            m_prop = self._re_property.match(line)
            if m_prop and depth == 1:
                key, value = m_prop.group(1), m_prop.group(2)
                self._apply_node_property(node, key, value)
                i += 1
                continue

            i += 1

        # 合并内部对象
        # T3D 格式中，同一个内部对象会出现两次：
        # 第一次有 Class（声明），第二次有属性（定义）
        merged = self._merge_inner_objects(inner_objects)
        if merged:
            node.material_expression = merged

        return node, i

    def _parse_inner_object(self, lines: List[str], start: int) -> Tuple[Optional[T3DInnerObject], int]:
        """解析嵌套的 Begin Object ... End Object"""
        m = self._re_begin.match(lines[start])
        if not m:
            return None, start

        obj = T3DInnerObject()
        obj.class_path = m.group(1) or ''
        obj.name = m.group(2) or ''
        obj.archetype = m.group(3) or ''

        # 从 class_path 提取 class_name
        if obj.class_path:
            obj.class_name = obj.class_path.rsplit('.', 1)[-1] if '.' in obj.class_path else obj.class_path

        depth = 1
        i = start + 1

        while i < len(lines) and depth > 0:
            line = lines[i]

            if self._re_end.match(line):
                depth -= 1
                if depth == 0:
                    break
                i += 1
                continue

            if self._re_begin.match(line):
                depth += 1
                i += 1
                continue

            # 属性
            m_prop = self._re_property.match(line)
            if m_prop:
                key, value = m_prop.group(1), m_prop.group(2)
                # 对于 Code 属性，进行反转义（从 T3D 的转义格式恢复真实换行符）
                if key == 'Code' and value.startswith('"') and value.endswith('"'):
                    unescaped_inner = _unescape_t3d_string(value[1:-1])
                    obj.properties[key] = f'"{unescaped_inner}"'
                else:
                    obj.properties[key] = value

            i += 1

        return obj, i

    def _merge_inner_objects(self, objects: List[T3DInnerObject]) -> Optional[T3DInnerObject]:
        """合并同名的声明和定义对象"""
        if not objects:
            return None

        by_name: Dict[str, T3DInnerObject] = {}
        for obj in objects:
            if obj.name in by_name:
                # 合并属性
                existing = by_name[obj.name]
                if obj.class_path and not existing.class_path:
                    existing.class_path = obj.class_path
                    existing.class_name = obj.class_name
                if obj.archetype and not existing.archetype:
                    existing.archetype = obj.archetype
                existing.properties.update(obj.properties)
            else:
                by_name[obj.name] = obj

        # 返回第一个（通常只有一个内部 MaterialExpression）
        result = list(by_name.values())
        return result[0] if result else None

    def _apply_node_property(self, node: T3DGraphNode, key: str, value: str):
        """应用节点属性"""
        if key == 'NodePosX':
            try:
                node.node_pos_x = int(float(value))
            except (ValueError, TypeError):
                node.node_pos_x = 0
        elif key == 'NodePosY':
            try:
                node.node_pos_y = int(float(value))
            except (ValueError, TypeError):
                node.node_pos_y = 0
        elif key == 'NodeGuid':
            node.node_guid = value
        elif key == 'MaterialExpression':
            node.material_expression_ref = value
        elif key == 'ErrorMsg':
            # 去除转义引号
            msg = value.strip('"').replace('\\"', '"')
            node.error_messages.append(msg)
        else:
            node.properties[key] = value

    def _parse_pin(self, pin_text: str) -> T3DPin:
        """解析一个 Pin 的属性文本
        
        格式: PinId=GUID,PinName="...",Direction="EGPD_Output",...
        需要处理嵌套括号（如 LinkedTo=(...)）和引号
        """
        pin = T3DPin()
        props = self._tokenize_pin_props(pin_text)

        for key, value in props.items():
            value_clean = value.strip('"')
            
            if key == 'PinId':
                pin.pin_id = value_clean
            elif key == 'PinName':
                pin.pin_name = value_clean
            elif key == 'PinFriendlyName':
                pin.pin_friendly_name = value_clean
            elif key == 'Direction':
                # 可能是 "EGPD_Output" 或 "EEdGraphPinDirection::EGPD_Output"
                if 'EGPD_Output' in value_clean:
                    pin.direction = 'EGPD_Output'
                else:
                    pin.direction = 'EGPD_Input'
            elif key == 'PinType.PinCategory':
                pin.pin_type_category = value_clean
            elif key == 'PinType.PinSubCategory':
                pin.pin_type_sub_category = value_clean
            elif key == 'PinType.PinSubCategoryObject':
                pin.pin_type_sub_category_object = value_clean
            elif key == 'DefaultValue':
                pin.default_value = value_clean
            elif key == 'AutogeneratedDefaultValue':
                pin.autogenerated_default_value = value_clean
            elif key == 'LinkedTo':
                pin.linked_to = self._parse_linked_to(value)
            elif key == 'PersistentGuid':
                pin.persistent_guid = value_clean
            elif key == 'bHidden':
                pin.is_hidden = value_clean.lower() == 'true'
            elif key == 'bNotConnectable':
                pin.is_not_connectable = value_clean.lower() == 'true'
            elif key == 'bAdvancedView':
                pin.is_advanced_view = value_clean.lower() == 'true'
            elif key == 'bOrphanedPin':
                pin.is_orphaned = value_clean.lower() == 'true'
            else:
                pin.raw_props[key] = value

        return pin

    def _tokenize_pin_props(self, text: str) -> Dict[str, str]:
        """将 Pin 属性文本 tokenize 为 key=value 对
        
        需要处理:
        - 普通值: PinId=ABC123
        - 引号值: PinName="A"
        - 嵌套括号: LinkedTo=(MaterialGraphNode_1 ABC123,)
        - PinType 子属性: PinType.PinCategory="float"
        """
        props = {}
        i = 0
        text = text.strip()
        
        while i < len(text):
            # 跳过逗号和空格
            while i < len(text) and text[i] in (',', ' ', '\t'):
                i += 1
            if i >= len(text):
                break

            # 读取 key
            key_start = i
            while i < len(text) and text[i] not in ('=', ',', ' '):
                i += 1
            key = text[key_start:i]
            
            if not key or i >= len(text) or text[i] != '=':
                i += 1
                continue

            i += 1  # 跳过 =
            
            # 读取 value
            if i >= len(text):
                props[key] = ''
                break
                
            if text[i] == '"':
                # 引号值 - 找到匹配的闭合引号
                i += 1
                value_start = i
                while i < len(text):
                    if text[i] == '\\' and i + 1 < len(text):
                        i += 2
                        continue
                    if text[i] == '"':
                        break
                    i += 1
                value = text[value_start:i]
                if i < len(text):
                    i += 1  # 跳过闭合引号
                props[key] = f'"{value}"'
                
            elif text[i] == '(':
                # 括号值（如 LinkedTo=(...)）
                depth = 1
                i += 1
                value_start = i
                while i < len(text) and depth > 0:
                    if text[i] == '(':
                        depth += 1
                    elif text[i] == ')':
                        depth -= 1
                    i += 1
                value = text[value_start:i-1]  # 不包含外层括号
                props[key] = f'({value})'
                
            else:
                # 普通值
                value_start = i
                while i < len(text) and text[i] not in (',', ' ', '\t', ')'):
                    i += 1
                props[key] = text[value_start:i]

        return props

    def _parse_linked_to(self, value: str) -> List[Tuple[str, str]]:
        """解析 LinkedTo 值
        
        格式: (MaterialGraphNode_0 4C8598EE...,MaterialGraphNode_1 A1B2C3D4...,)
        """
        result = []
        # 去掉外层括号
        inner = value.strip()
        if inner.startswith('('):
            inner = inner[1:]
        if inner.endswith(')'):
            inner = inner[:-1]
        
        if not inner.strip():
            return result
        
        # 按逗号分割
        parts = inner.split(',')
        for part in parts:
            part = part.strip()
            if not part:
                continue
            # "NodeName PinGuid" 格式
            tokens = part.split(' ', 1)
            if len(tokens) == 2:
                result.append((tokens[0], tokens[1]))
            elif len(tokens) == 1 and tokens[0]:
                # 可能只有 NodeName
                result.append((tokens[0], ''))

        return result


# ═══════════════════════════════════════════════════════════
# 转换为内部 MaterialGraph（复用 node_mapper 的数据结构）
# ═══════════════════════════════════════════════════════════

def t3d_to_graph_data(parse_result: T3DParseResult) -> dict:
    """将 T3D 解析结果转换为前端可用的图数据 JSON
    
    返回的格式与 web_server.py 的 graph_to_json() 兼容
    """
    from graph_visualizer import NODE_COLORS, DEFAULT_COLOR

    nodes_data = []
    connections = []
    node_name_to_idx = {}  # NodeName -> 节点索引

    # 第一遍：收集所有节点信息
    for idx, node in enumerate(parse_result.nodes):
        node_name_to_idx[node.name] = idx

        # 确定 UE 类名
        ue_class = ''
        if node.material_expression:
            ue_class = node.material_expression.class_name
        elif node.class_path:
            ue_class = node.class_path.rsplit('.', 1)[-1] if '.' in node.class_path else node.class_path

        # 确定显示名称
        display_name = _get_display_name(ue_class, node)

        # 获取颜色
        color = NODE_COLORS.get(ue_class, DEFAULT_COLOR)

        # 收集输入 pin 名称
        input_pins = [p for p in node.pins if p.direction == 'EGPD_Input' and not p.is_hidden]
        output_pins = [p for p in node.pins if p.direction == 'EGPD_Output' and not p.is_hidden]

        # 属性字符串
        props_str = ''
        if node.material_expression and node.material_expression.properties:
            props_parts = []
            for k, v in node.material_expression.properties.items():
                # 过滤掉一些内部属性
                if k.startswith('MaterialExpression') and k.endswith('Guid'):
                    continue
                props_parts.append(f'{k} = {v}')
            if props_parts:
                props_str = '\n'.join(props_parts)

        # 判断节点类型
        is_output = ('MaterialResult' in node.name or 
                     'Root' in node.name or
                     ue_class == 'MaterialGraphNode_Root')
        is_input = ue_class in ('MaterialExpressionFunctionInput',
                                'MaterialExpressionScalarParameter',
                                'MaterialExpressionVectorParameter',
                                'MaterialExpressionStaticBoolParameter',
                                'MaterialExpressionStaticSwitchParameter')
        is_builtin = (ue_class.startswith('MaterialExpressionCamera') or
                      ue_class.startswith('MaterialExpressionWorld') or
                      ue_class.startswith('MaterialExpressionPixelNormal') or
                      ue_class.startswith('MaterialExpressionVertexNormal') or
                      (ue_class.startswith('MaterialExpressionTexture') and 'Coordinate' in ue_class) or
                      ue_class == 'MaterialExpressionTime' or
                      ue_class == 'MaterialExpressionScreenPosition' or
                      ue_class == 'MaterialExpressionVertexColor' or
                      ue_class.startswith('MaterialExpressionReflectionVector') or
                      ue_class.startswith('MaterialExpressionObject') or
                      ue_class.startswith('MaterialExpressionActor') or
                      ue_class == 'MaterialExpressionPixelDepth' or
                      ue_class == 'MaterialExpressionSceneDepth')

        nodes_data.append({
            'id': idx,
            'name': node.name,  # T3D 原始节点名
            'display_name': display_name,
            'ue_class': ue_class,
            'x': node.node_pos_x,
            'y': node.node_pos_y,
            'color': color,
            'inputs': [],  # 稍后填充
            'input_names': [p.pin_name for p in input_pins],
            'output_names': [p.pin_name for p in output_pins],
            'properties': props_str,
            'is_output': is_output,
            'is_input': is_input,
            'is_builtin': is_builtin,
            'source_line': '',
            'pins': _serialize_pins(node.pins),  # 保存完整 pin 信息
        })

    # 第二遍：建立连线
    # 从 LinkedTo 信息建立连线关系
    for idx, node in enumerate(parse_result.nodes):
        for pin in node.pins:
            if pin.direction == 'EGPD_Input' and pin.linked_to:
                for target_node_name, target_pin_id in pin.linked_to:
                    if target_node_name in node_name_to_idx:
                        from_idx = node_name_to_idx[target_node_name]
                        # 找到输入 pin 在输入 pin 列表中的索引
                        input_pins = [p for p in node.pins if p.direction == 'EGPD_Input' and not p.is_hidden]
                        to_pin_index = 0
                        for pi, p in enumerate(input_pins):
                            if p.pin_id == pin.pin_id:
                                to_pin_index = pi
                                break
                        
                        connections.append({
                            'from_id': from_idx,
                            'to_id': idx,
                            'to_pin_index': to_pin_index,
                            'label': pin.pin_name,
                        })
                        
                        # 也更新 inputs
                        nodes_data[idx]['inputs'].append({
                            'name': pin.pin_name,
                            'source_id': from_idx,
                        })

    # 自动平移坐标使其可见（UE4 可能有负坐标）
    if nodes_data:
        min_x = min(n['x'] for n in nodes_data)
        min_y = min(n['y'] for n in nodes_data)
        offset_x = -min_x + 50 if min_x < 50 else 0
        offset_y = -min_y + 50 if min_y < 50 else 0
        for n in nodes_data:
            n['x'] += offset_x
            n['y'] += offset_y

    return {
        'nodes': nodes_data,
        'connections': connections,
        'warnings': parse_result.warnings,
        'custom_expressions': [],
        'stats': {
            'node_count': len(nodes_data),
            'input_count': sum(1 for n in nodes_data if n['is_input']),
            'connection_count': len(connections),
        }
    }


def _serialize_pins(pins: List[T3DPin]) -> List[dict]:
    """序列化 pin 列表为 JSON 兼容格式"""
    result = []
    for p in pins:
        result.append({
            'pin_id': p.pin_id,
            'pin_name': p.pin_name,
            'pin_friendly_name': p.pin_friendly_name,
            'direction': p.direction,
            'pin_type_category': p.pin_type_category,
            'default_value': p.default_value,
            'autogenerated_default_value': p.autogenerated_default_value,
            'linked_to': [{'node': n, 'pin': g} for n, g in p.linked_to],
            'is_hidden': p.is_hidden,
            'is_orphaned': p.is_orphaned,
            'raw_props': p.raw_props,
        })
    return result


# ═══════════════════════════════════════════════════════════
# UE class → 友好显示名
# ═══════════════════════════════════════════════════════════

_DISPLAY_NAMES = {
    'MaterialExpressionAdd': 'Add',
    'MaterialExpressionSubtract': 'Subtract',
    'MaterialExpressionMultiply': 'Multiply',
    'MaterialExpressionDivide': 'Divide',
    'MaterialExpressionPower': 'Power',
    'MaterialExpressionAbs': 'Abs',
    'MaterialExpressionCeil': 'Ceil',
    'MaterialExpressionFloor': 'Floor',
    'MaterialExpressionFrac': 'Frac',
    'MaterialExpressionFmod': 'Fmod',
    'MaterialExpressionMin': 'Min',
    'MaterialExpressionMax': 'Max',
    'MaterialExpressionClamp': 'Clamp',
    'MaterialExpressionSaturate': 'Saturate',
    'MaterialExpressionOneMinus': 'One Minus',
    'MaterialExpressionSign': 'Sign',
    'MaterialExpressionTruncate': 'Truncate',
    'MaterialExpressionRound': 'Round',
    'MaterialExpressionSquareRoot': 'Sqrt',
    'MaterialExpressionSine': 'Sine',
    'MaterialExpressionCosine': 'Cosine',
    'MaterialExpressionTangent': 'Tangent',
    'MaterialExpressionArcsine': 'Arcsine',
    'MaterialExpressionArcsineFast': 'Arcsine (Fast)',
    'MaterialExpressionArccosine': 'Arccosine',
    'MaterialExpressionArccosineFast': 'Arccosine (Fast)',
    'MaterialExpressionArctangent': 'Arctangent',
    'MaterialExpressionArctangentFast': 'Arctangent (Fast)',
    'MaterialExpressionArctangent2': 'Arctangent2',
    'MaterialExpressionArctangent2Fast': 'Arctangent2 (Fast)',
    'MaterialExpressionDotProduct': 'Dot',
    'MaterialExpressionCrossProduct': 'Cross',
    'MaterialExpressionDistance': 'Distance',
    'MaterialExpressionNormalize': 'Normalize',
    'MaterialExpressionLinearInterpolate': 'Lerp',
    'MaterialExpressionIf': 'If',
    'MaterialExpressionConstant': 'Constant',
    'MaterialExpressionConstant2Vector': 'Constant2',
    'MaterialExpressionConstant3Vector': 'Color (RGB)',
    'MaterialExpressionConstant4Vector': 'Color (RGBA)',
    'MaterialExpressionAppendVector': 'Append',
    'MaterialExpressionComponentMask': 'Mask',
    'MaterialExpressionStaticSwitch': 'Static Switch',
    'MaterialExpressionStaticBool': 'Static Bool',
    'MaterialExpressionScalarParameter': 'Scalar Param',
    'MaterialExpressionVectorParameter': 'Vector Param',
    'MaterialExpressionStaticBoolParameter': 'Bool Param',
    'MaterialExpressionStaticSwitchParameter': 'Switch Param',
    'MaterialExpressionTextureSample': 'Texture Sample',
    'MaterialExpressionTextureSampleParameter2D': 'Texture Param',
    'MaterialExpressionTextureCoordinate': 'TexCoord',
    'MaterialExpressionTextureObject': 'Texture Object',
    'MaterialExpressionTextureObjectParameter': 'Texture Obj Param',
    'MaterialExpressionTime': 'Time',
    'MaterialExpressionCameraPositionWS': 'Camera Pos (WS)',
    'MaterialExpressionCameraVectorWS': 'Camera Vec (WS)',
    'MaterialExpressionWorldPosition': 'World Pos',
    'MaterialExpressionObjectPositionWS': 'Object Pos (WS)',
    'MaterialExpressionPixelNormalWS': 'Pixel Normal (WS)',
    'MaterialExpressionVertexNormalWS': 'Vertex Normal (WS)',
    'MaterialExpressionVertexTangentWS': 'Vertex Tangent (WS)',
    'MaterialExpressionVertexColor': 'Vertex Color',
    'MaterialExpressionScreenPosition': 'Screen Pos',
    'MaterialExpressionPixelDepth': 'Pixel Depth',
    'MaterialExpressionSceneDepth': 'Scene Depth',
    'MaterialExpressionReflectionVectorWS': 'Reflection Vec',
    'MaterialExpressionPanner': 'Panner',
    'MaterialExpressionRotator': 'Rotator',
    'MaterialExpressionTransform': 'Transform',
    'MaterialExpressionTransformPosition': 'Transform Position',
    'MaterialExpressionCustom': 'Custom',
    'MaterialExpressionFunctionInput': 'Function Input',
    'MaterialExpressionFunctionOutput': 'Function Output',
    'MaterialExpressionMaterialFunctionCall': 'Material Function',
    'MaterialExpressionReroute': 'Reroute',
    'MaterialExpressionComment': 'Comment',
    'MaterialExpressionBlackBody': 'BlackBody',
    'MaterialExpressionSphereMask': 'Sphere Mask',
    'MaterialExpressionStep': 'Step',
    'MaterialExpressionSmoothStep': 'SmoothStep',
    'MaterialExpressionLength': 'Length',
    'MaterialExpressionDDX': 'DDX',
    'MaterialExpressionDDY': 'DDY',
    'MaterialExpressionDesaturation': 'Desaturation',
    'MaterialExpressionFresnel': 'Fresnel',
    'MaterialExpressionFeatureLevelSwitch': 'Feature Level Switch',
    'MaterialExpressionQualitySwitch': 'Quality Switch',
    'MaterialExpressionShadingModel': 'Shading Model',
    'MaterialExpressionBumpOffset': 'Bump Offset',
    'MaterialExpressionParallaxOcclusionMapping': 'POM',
    'MaterialExpressionDepthFade': 'Depth Fade',
    'MaterialExpressionTwoSidedSign': 'Two Sided Sign',
    'MaterialExpressionObjectRadius': 'Object Radius',
    'MaterialExpressionObjectBounds': 'Object Bounds',
    'MaterialExpressionActorPositionWS': 'Actor Pos (WS)',
    'MaterialGraphNode_Root': 'Material Output',
}


def _get_display_name(ue_class: str, node: T3DGraphNode) -> str:
    """获取友好显示名"""
    if ue_class in _DISPLAY_NAMES:
        name = _DISPLAY_NAMES[ue_class]
    else:
        # 从类名提取
        name = ue_class.replace('MaterialExpression', '').replace('MaterialGraphNode_', '')
        if not name:
            name = node.name

    # 对某些特殊节点增加额外信息
    if node.material_expression:
        props = node.material_expression.properties
        if ue_class == 'MaterialExpressionConstant' and 'R' in props:
            name = f'Const ({props["R"]})'
        elif ue_class == 'MaterialExpressionConstant3Vector' and 'Constant' in props:
            name = f'Color {props["Constant"][:30]}'
        elif ue_class == 'MaterialExpressionScalarParameter' and 'ParameterName' in props:
            pname = props['ParameterName'].strip('"')
            name = f'Param: {pname}'
        elif ue_class == 'MaterialExpressionVectorParameter' and 'ParameterName' in props:
            pname = props['ParameterName'].strip('"')
            name = f'Vec Param: {pname}'
        elif ue_class == 'MaterialExpressionCustom' and 'Description' in props:
            desc = props['Description'].strip('"')
            name = f'Custom: {desc[:20]}'
        elif ue_class == 'MaterialExpressionFunctionInput' and 'InputName' in props:
            iname = props['InputName'].strip('"')
            name = f'Input: {iname}'
        elif ue_class == 'MaterialExpressionTextureCoordinate' and 'CoordinateIndex' in props:
            ci = props['CoordinateIndex']
            name = f'TexCoord [{ci}]'

    return name


# ═══════════════════════════════════════════════════════════
# 便捷接口
# ═══════════════════════════════════════════════════════════

def parse_t3d_clipboard(text: str) -> dict:
    """一步完成：解析 T3D 文本 → 返回前端可用的图数据 JSON"""
    parser = T3DParser()
    result = parser.parse(text)
    
    if result.errors:
        return {
            'error': '\n'.join(result.errors),
            'warnings': result.warnings,
        }
    
    graph_data = t3d_to_graph_data(result)
    graph_data['warnings'].extend(result.warnings)
    
    return {
        'graph': graph_data,
        'node_count': len(result.nodes),
    }


def parse_t3d_to_result(text: str) -> T3DParseResult:
    """解析 T3D 文本返回原始解析结果"""
    parser = T3DParser()
    return parser.parse(text)
